name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Build Extension
        run: pnpm run build

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "web-ext-artifacts/*"
          makeLatest: true
      
      - uses: ./.github/workflows/web-ext-publish.yml