# This workflow will publish an extension for Firefox when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - run: pnpm build
      - run: pnpm publish
        env:
          WEB_EXT_API_KEY: ${{secrets.web_ext_api_key}}
          WEB_EXT_API_SECRET: ${{secrets.web_ext_api_secret}}
