# This workflow will publish an extension for Firefox when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Firefox Publish

on:
  release:
    types: [created]

jobs:
  publish-firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Node.js dependencies
        run: pnpm install
      
      - name: Publish Extension
        run: pnpm run publish
        env:
          WEB_EXT_API_KEY: ${{secrets.web_ext_api_key}}
          WEB_EXT_API_SECRET: ${{secrets.web_ext_api_secret}}
